run:
  deadline: 5m

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  disable:
    - wsl
    - lll

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - linters:
        - gosec
      text: "G104: Errors unhandled"

# output configuration options
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
